### ISSUE TITLE
package fails to build on linux gcc 4.8, x86_64 

### ISSUE THREAD

**Issue by weatherhead99** [kmaragon/conan-bzip2#1]
> conan install --build bzip2/1.0.6@kmaragon/stable

`ERROR: bzip2/1.0.6@kmaragon/stable: Error in source() method, line 29
	tools.replace_in_file(makeshared, "PREFIX=", "PREFIX?=")
	ConanException: replace_in_file didn't find pattern 'PREFIX=' in 'bzip2-1.0.6/Makefile-libbz2_so' file.
`

Thanks! :-)

**Comment by kmaragon** [comment]
This is probably less to do with gcc 4.8 and more to do with the source package changing. I think I saw this before and fixed it in a local repo since conan-transit is read-only (as such, I won't be able to push a fix there)

**Comment by weatherhead99** [comment]
ok, thanks :-) yes I can fix it in the local cache too.
There are definitely some disadvantages from conan moving to bintray, I think :-)

**Comment by kmaragon** [comment]
Actually it's already fixed in the GitHub repo. It's just that I couldn't push that fix to conan-transit

**Comment by weatherhead99** [comment]
great - do you have a bintray remote I can add?

**Comment by kmaragon** [comment]
I didn't want to maintain a bzip2 package but had problems with lasotes back in the conan 0.1x.y days. But I'll push it up :-)

**Comment by kmaragon** [comment]
To https://bintray.com/kmaragon/conan

**Comment by kmaragon** [comment]
Actually I take it back. I've had reasonable success now with lasote's. I'll recommend that one.

https://bintray.com/conan-community/conan
